// Jotform configuration & program field requirements
const JOTFORM_CONFIG = {
  swt: {
    label: 'Summer Work & Travel',
    formId: '60317934048860',
    submitUrl: 'https://submit.jotform.com/submit/60317934048860',
    icon: 'sun',
    color: '#FFD731',
    fields: {
      firstName: 'q15_nombreCompleto[first]',
      lastName: 'q15_nombreCompleto[last]',
      phoneArea: 'q19_numeroDe[area]',
      phoneNumber: 'q19_numeroDe[phone]',
      email: 'q18_correoElectronico18',
      dobMonth: 'q27_fechaDe27[month]',
      dobDay: 'q27_fechaDe27[day]',
      dobYear: 'q27_fechaDe27[year]',
      residence: 'q33_lugarDe33',
      university: 'q26_universidad26',
      semesterAndCareer: 'q35_semestreY',
      englishLevel: 'q12_nivelDe12',
      whyParticipate: 'q20_porqueQuieres',
      howFound: 'q21_comoTe21',
      acceptTerms: 'q25_aceptoLos[]',
    },
    englishMap: { intermedio: 'Intermedio', avanzado: 'Avanzado' },
    needs: ['career', 'semester', 'why'],
  },
  camp: {
    label: 'Camp Exchange',
    formId: '60166650342854',
    submitUrl: 'https://submit.jotform.com/submit/60166650342854',
    icon: 'tent',
    color: '#639917',
    fields: {
      firstName: 'q15_nombreCompleto15[first]',
      lastName: 'q15_nombreCompleto15[last]',
      phoneArea: 'q19_numeroDe19[area]',
      phoneNumber: 'q19_numeroDe19[phone]',
      email: 'q18_correoElectronico',
      dobMonth: 'q27_fechaDe[month]',
      dobDay: 'q27_fechaDe[day]',
      dobYear: 'q27_fechaDe[year]',
      residence: 'q33_lugarDe33',
      university: 'q26_universidad',
      englishLevel: 'q12_nivelDe',
      skills: 'q13_input13[]',
      experienceSkills: 'q20_experienciaEn',
      experienceKids: 'q21_experienciaCon',
      aptitudes: 'q22_aptitudes',
      availability: 'q23_disponibilidadDe',
      howFound: 'q24_comoTe',
      acceptTerms: 'q25_aceptoLos[]',
    },
    englishMap: { intermedio: 'Intermedio', avanzado: 'Avanzado' },
    needs: ['skills', 'expSkills', 'expKids', 'aptitudes', 'availability'],
  },
  intern: {
    label: 'Internship & Trainee',
    formId: '60494938703868',
    submitUrl: 'https://submit.jotform.com/submit/60494938703868',
    icon: 'briefcase',
    color: '#196084',
    fields: {
      firstName: 'q15_fullName[first]',
      lastName: 'q15_fullName[last]',
      phoneArea: 'q19_phoneNumber[area]',
      phoneNumber: 'q19_phoneNumber[phone]',
      email: 'q18_email18',
      dobMonth: 'q27_dateOf[month]',
      dobDay: 'q27_dateOf[day]',
      dobYear: 'q27_dateOf[year]',
      residence: 'q33_placeOf',
      university: 'q26_university',
      occupation: 'q35_occupation',
      englishLevel: 'q12_englishLevel',
      whyParticipate: 'q20_whyDo',
      howFound: 'q21_howDid',
      acceptTerms: 'q25_iAccept[]',
    },
    englishMap: { intermedio: 'Intermediate', avanzado: 'Advanced' },
    needs: ['occupation', 'why'],
  },
  support: {
    label: 'Support Staff',
    formId: '261248592045863',
    submitUrl: 'https://submit.jotform.com/submit/261248592045863',
    icon: 'chef',
    color: '#FF6100',
    fields: {
      firstName: 'q15_nombreCompleto[first]',
      lastName: 'q15_nombreCompleto[last]',
      phoneArea: 'q19_numeroDe[area]',
      phoneNumber: 'q19_numeroDe[phone]',
      email: 'q18_correoElectronico18',
      dobMonth: 'q27_fechaDe27[month]',
      dobDay: 'q27_fechaDe27[day]',
      dobYear: 'q27_fechaDe27[year]',
      residence: 'q33_lugarDe33',
      university: 'q26_universidad26',
      semesterAndCareer: 'q35_semestreY',
      englishLevel: 'q12_nivelDe12',
      whyParticipate: 'q20_porqueQuieres',
      howFound: 'q21_comoTe21',
      acceptTerms: 'q25_aceptoLos[]',
    },
    englishMap: { intermedio: 'Intermedio', avanzado: 'Avanzado' },
    needs: ['career', 'semester', 'why'],
  },
};

const SKILLS_27 = [
  'Soccer', 'Volleyball', 'Béisbol', 'Softball', 'Tenis', 'Basquetbol',
  'Golf', 'Gimnasia', 'Esgrima', 'Natación', 'Ski Acuático', 'Wakeboard',
  'Navegación acuática', 'Kayak', 'Velero', 'Salvavidas', 'Esnorqueleo',
  'Patineta', 'Surf', 'Bici de montaña', 'Campismo', 'Rapeleo', 'Escalar',
  'Circo', 'Tiro con arco', 'Magia', 'Tiro con rifle',
];

const MONTHS_ES = [
  'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre',
];

Object.assign(window, { JOTFORM_CONFIG, SKILLS_27, MONTHS_ES });
